package com.bjpowernode.secondshop.settings.domain;

public class FirstType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column first_type.id
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column first_type.name
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column first_type.id
     *
     * @return the value of first_type.id
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column first_type.id
     *
     * @param id the value for first_type.id
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column first_type.name
     *
     * @return the value of first_type.name
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column first_type.name
     *
     * @param name the value for first_type.name
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}