package com.bjpowernode.secondshop.settings.domain;

public class SecondType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_type.id
     *
     * @mbggenerated Thu Jan 26 17:36:47 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_type.first_type_id
     *
     * @mbggenerated Thu Jan 26 17:36:47 CST 2023
     */
    private Integer firstTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_type.name
     *
     * @mbggenerated Thu Jan 26 17:36:47 CST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_type.id
     *
     * @return the value of second_type.id
     *
     * @mbggenerated Thu Jan 26 17:36:47 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_type.id
     *
     * @param id the value for second_type.id
     *
     * @mbggenerated Thu Jan 26 17:36:47 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_type.first_type_id
     *
     * @return the value of second_type.first_type_id
     *
     * @mbggenerated Thu Jan 26 17:36:47 CST 2023
     */
    public Integer getFirstTypeId() {
        return firstTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_type.first_type_id
     *
     * @param firstTypeId the value for second_type.first_type_id
     *
     * @mbggenerated Thu Jan 26 17:36:47 CST 2023
     */
    public void setFirstTypeId(Integer firstTypeId) {
        this.firstTypeId = firstTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_type.name
     *
     * @return the value of second_type.name
     *
     * @mbggenerated Thu Jan 26 17:36:47 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_type.name
     *
     * @param name the value for second_type.name
     *
     * @mbggenerated Thu Jan 26 17:36:47 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}