package com.bjpowernode.secondshop.settings.mapper;

import com.bjpowernode.secondshop.settings.domain.FirstType;

import java.util.List;

public interface FirstTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_type
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_type
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    int insert(FirstType firstType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_type
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    int insertSelective(FirstType firstType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_type
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    FirstType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_type
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    int updateByPrimaryKeySelective(FirstType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table first_type
     *
     * @mbggenerated Thu Jan 26 17:16:10 CST 2023
     */
    int updateByPrimaryKey(FirstType record);

    /**
     * 查询商品的所有的一级类型
     * @return
     */
    List<FirstType> selectAllFirstType();

    /**
     * 删除一级分类
     * @param firstTypeId
     * @return
     */
    int deleteFirstTypeById(Integer firstTypeId);


}